[package]
authors = ["madetara x@madetara.dev"]
name = "ttembedder"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
bench = false
name = "ttembedder"
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
lazy_static = "1.4.0"
teloxide = { version = "0.12", features = ["macros", "webhooks-axum"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
url = "2.2.2"
uuid = "1.5.0"
